### ISSUE TITLE
how is systemstat related to the get_sys_info crate?

### ISSUE THREAD

**Issue by bbigras** [unrelentingtech/systemstat#105]
Is [get_sys_info](https://lib.rs/crates/get_sys_info) a fork?

I just want to know which is the original crate.

**Comment by unrelentingtech** [comment]
Seems to be. It's kind of a suspicious fork, completely changed authorship information and readme is the only obvious change.

Didn't even bother to edit the URLs for the little badge images:

```
[![crates.io](https://img.shields.io/crates/v/systemstat.svg)](https://crates.io/crates/get_sys_info)
[![API Docs](https://docs.rs/systemstat/badge.svg)](https://docs.rs/get_sys_info/)
```

There isn't even a github repo linked.

**Comment by unrelentingtech** [comment]
No, it doesn't. This is fine legally, just weird.

**Comment by bbigras** [comment]
Gotcha, thanks.
