### ISSUE TITLE
Can't get memory usage on macOS 

### ISSUE THREAD

**Issue by Varkal** [unrelentingtech/systemstat#73]
This code : 

```
let sys = System::new();
let memory_usage = sys.memory().unwrap()
```
Panic with this error message : 

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Not supported" }', src/main.rs:36:24

**Comment by myfreeweb** [comment]
Yes, nobody has implemented this here. Feel free to make a PR :)

or, [check out other similar crates](https://github.com/heim-rs/heim/blob/master/COMPARISON.md).
