### ISSUE TITLE
How to get cpu usage

### ISSUE THREAD

**Issue by rustbomb** [unrelentingtech/systemstat#87]

**Comment by unrelentingtech** [comment]
See the `examples` directory in the repo. Also #84.

**Comment by rustbomb** [comment]
I thank cpu usage is different cpu_load_aggregate.

**Comment by unrelentingtech** [comment]
What other kind of usage is there? I'm not aware of any other ways to measure CPU usage than what's implemented as `cpu_load_aggregate`.
