### ISSUE TITLE
Swap support

### ISSUE THREAD

**Issue by davidkna** [unrelentingtech/systemstat#93]
In addition to `memory()`-usage also report swap usage. I would be willing to implement this myself.

Would you prefer this as a separate `swap()` function or as a part of `memory()`? Some platform-APIs will return memory and swap information together.

**Comment by davidkna** [comment]
So would you accept a PR with initial swap support for Linux, macOS and Windows? I think putting it into a separate function best and maybe implementing `TryFrom` between memory and swap types.

**Comment by unrelentingtech** [comment]
Yes, sure, let's see how that looks
