### ISSUE TITLE
Invoking networks() results in STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Snazzie** [unrelentingtech/systemstat#95]
```rs
fn main() {
   let sys_stat = systemstat::System::new();
   do_something(&sys_stat);
}

fn do_something(sys_stat: &systemstat::System) {
    let net = sys_stat.networks(); // crash (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
}
```
platform: windows 11
version: 0.1.10

**Comment by unrelentingtech** [comment]
In the current version, networks do work for me on Windows 11.

**Comment by Snazzie** [comment]
Just tested again, it doesnt for me 🤷 

https://github.com/Snazzie/systemstat-access-violation-bug

**Comment by George-Strike** [comment]
I'm getting the same issue. `(exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)`

**Comment by unrelentingtech** [comment]
I guess this only happens when there are enough network adapters to trigger it. I think I see the bug from a quick look at the code, can someone test db66afe0fd804?

**Comment by Snazzie** [comment]
@unrelentingtech yes, that fixed it 🎊 . I have 14 adapters on my machine (loads of virtual ones)
