### ISSUE TITLE
Cross-compil from Linux to Windows failed

### ISSUE THREAD

**Issue by Dalan94** [unrelentingtech/systemstat#96]
When building my application which use systemstat from a Linux host to a windows target (`cargo build --target=x86_64-pc-windows-gnu ` the linker failed (` /usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lIphlpapi`).
The problem is that the library in mingw is in totally in lowercase (iphlpapi) but the linker attribute (in socket.rs and network_interfaces.rs) has the first letter in uppercase (Iphlpapi).
Could you change the linker attributes to make the build succeed.
It shouldn't change the Windows behavior because the filename are case insensitive in Windows.

Regards

**Comment by unrelentingtech** [comment]
We don't link anything directly here, I'm pretty sure this is part of the `winapi` crate.

**Comment by unrelentingtech** [comment]
oh, haven't checked `socket`. Can you send a pull request?
